### PR TITLE
Mostly general annotations

### PR DESCRIPTION
**Pull request by saltastroops**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
Did you check issues raised by `mypy` there are quite a few of them?

> Reviewed 104 of 104 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1#-:-Muu4NKQ0kxZk0ykIj29:bmfvkm8)* status: all files reviewed, 11 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[docs/development.md, line 54 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutjuN4EN9gvO9Fq9Ej:-MutjuNI02ZDwmR_S0aE:b-ojyyl0) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/docs/development.md#L54)):*
> ```Markdown
> sphinx-build | `sphinx-build docs docs/build` | Build the documentation.
> 
> ## Testing with tox
> ```

Shouldn't `tox` be listed in the `requirement-dev.txt` file?
___
*[src/imephu/finder_chart.py, line 62 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutmjWZCVHeGTW_bshM:-MutmjW_2Ht7PmkDEjpW:bf69nis) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/finder_chart.py#L62)):*
> ```Python
>             The center position of the loaded FITS file.
>         size: `~astropy.coordinates.Angle`
>             The width and height of the FITS file image, as an angle on the sky.
> ```

Maybe it might be useful to indicate the units of the angle?
___
*[src/imephu/geometry.py, line 23 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutoxsH-If-AAOououy:-MutoxsH-If-AAOououz:b-z37u2v) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/geometry.py#L23)):*
> ```Python
>     The angle is measured from north to south. Hence it depends on the orientation of
>     coordinate aces whether a positive angle corresponds to a clockwise or
>     anti-clockwise orientation.
> ```

... Hence it depends on the orientation of the coordinate axes ...



_Code quote:_
```Python
    The angle is measured from north to south. Hence it depends on the orientation of
    coordinate aces whether a positive angle corresponds to a clockwise or
    anti-clockwise orientation.
```
___
*[src/imephu/geometry.py, line 71 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Mutp9sq6AHGzTTXiYTc:-Mutp9sr0ts5o4tSxq0C:b6632uv) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/geometry.py#L71)):*
> ```Python
> 
> def translate(v: SkyCoord, displacement: Angle) -> SkyCoord:
>     """Move a point on the by a displacement vector.
> ```

Move a point on the chart/plot ...



_Code quote:_
```Python
  """Move a point on the by a displacement vector.
```
___
*[src/imephu/geometry.py, line 193 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutppxT72TQ05KbGzX_:-MutppxU1-NEGIXoL6jV:b-70h8vw) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/geometry.py#L193)):*
> ```Python
>     Return whether for a given WCS positive angles are anti-clockwise when plotted.
> 
>     Angles on the sky are measured from north to east, and depending on the axis
> ```

... and depending on the axis of orientation on the finder ...
___
*[src/imephu/annotation/general/arrow.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutqTIQ-3dA0S4XPFkj:-MutqTIQ-3dA0S4XPFkk:b-vvgal1) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L16)):*
> ```Python
> 
>     The start of the arrow's tail and the tip of the arrow's head are given as sky
>     positions (in right ascension and declination. The width and height of the arrow
> ```

(in right ascension and declination)... 
___
*[src/imephu/annotation/general/arrow.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutrKdADdRkcbQCX3YF:-MutrKdADdRkcbQCX3YG:b-yitzx6) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L26)):*
> ```Python
>     ----------
>     start: `~astropy.coordinates.SkyCoord`
>         Position of the arrow tail's start.
> ```

arrow tail's start ---> arrow's tail start



_Code quote:_
```Python
Position of the arrow tail's start.
```
___
*[src/imephu/annotation/general/arrow.py, line 28 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutrU07A3GguCMbEqog:-MutrU07A3GguCMbEqoh:b-ksgm0u) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L28)):*
> ```Python
>         Position of the arrow tail's start.
>     end: `~astropy.coordinates.SkyCoord`
>         Position of the arrow head's tip.
> ```

same as above, arrow's head tip 
___
*[src/imephu/annotation/general/circle.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Muts1uX426ooAXReUZq:-Muts1uX426ooAXReUZr:bxdz0jd) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/circle.py#L26)):*
> ```Python
>         The right ascension and declination of the circle's center.
>     radius: `~astropy.coordinates.Angle`
>         The circle radius, as an angular distance on the sky in right ascension
> ```

The circle's radius or radius of the circle
___
*[src/imephu/annotation/general/rectangle.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Mutt-Bl9W4i8wsOK06j:-Mutt-Bl9W4i8wsOK06k:b-wt39cc) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/rectangle.py#L17)):*
> ```Python
>     The rectangle is defined by its center, width and height. The center must be a sky
>     position in right ascension and declination, the width and height must be an angle
>     pm the sky. The width is taken to be the extension in the right ascension direction,
> ```

... must be an angle on the sky
___
*[src/imephu/service/survey.py, line 159 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Mutw5CN3ZjK5guK9x5c:-Mutw5CN3ZjK5guK9x5d:bwp6xcm) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/service/survey.py#L159)):*
> ```Python
>         -------
>         binary stream
>             The
> ```

"The" probably doesn't belong here or you forgot to finish up the sentence.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1)* status: 96 of 107 files reviewed, 11 unresolved discussions (waiting on @hettlage, @mofokeng-chaka, and @saltastroops)

___
*[docs/development.md, line 54 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutjuN4EN9gvO9Fq9Ej:-Muu7h6gAbIXTBNYeffh:b-896fix) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/docs/development.md#L54)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Shouldn't `tox` be listed in the `requirement-dev.txt` file?
</blockquote></details>

Done.
___
*[src/imephu/finder_chart.py, line 62 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutmjWZCVHeGTW_bshM:-MuuAckkE3mBaDbVG7ao:bpi839k) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/finder_chart.py#L62)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe it might be useful to indicate the units of the angle?
</blockquote></details>

No need. The joy of AstroPy quantities is that you specify them along with units.
___
*[src/imephu/geometry.py, line 23 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutoxsH-If-AAOououy:-MuuB7XH2a1RnwIY2N0c:bj3eoea) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/geometry.py#L23)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

... Hence it depends on the orientation of the coordinate axes ...
</blockquote></details>

Fixed, thanks.
___
*[src/imephu/geometry.py, line 71 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Mutp9sq6AHGzTTXiYTc:-MuuBMs62xrcAIKsowHT:buxdlxj) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/geometry.py#L71)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Move a point on the chart/plot ...
</blockquote></details>

Fixed. I don't think the chart needs to be mentioned.
___
*[src/imephu/geometry.py, line 193 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutppxT72TQ05KbGzX_:-MuuBtb22dgMzq_JAC7h:b499q7j) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/geometry.py#L193)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

... and depending on the axis of orientation on the finder ...
</blockquote></details>

Changed
___
*[src/imephu/annotation/general/arrow.py, line 16 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutqTIQ-3dA0S4XPFkj:-MuuC4DyBzWHfQfmq0uC:b-886gsx) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L16)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

(in right ascension and declination)... 
</blockquote></details>

Fixed
___
*[src/imephu/annotation/general/arrow.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutrKdADdRkcbQCX3YF:-MuuCHvm06aDcicQ7263:br7x2kr) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L26)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

arrow tail's start ---> arrow's tail start
</blockquote></details>

Actually I think my version is correct
___
*[src/imephu/annotation/general/arrow.py, line 28 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutrU07A3GguCMbEqog:-MuuCNKxC8-bIG-QFX-0:b-ya81ng) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L28)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

same as above, arrow's head tip 
</blockquote></details>

Same as above
___
*[src/imephu/annotation/general/circle.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Muts1uX426ooAXReUZq:-MuuCyhOAczlQTpF8Bsw:b-6bzogh) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/circle.py#L26)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

The circle's radius or radius of the circle
</blockquote></details>

I think "circle radius" is correct as well, but I've changed it.
___
*[src/imephu/annotation/general/rectangle.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Mutt-Bl9W4i8wsOK06j:-MuuDAUi5R1VYr78q6DN:b-886gsx) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/rectangle.py#L17)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

... must be an angle on the sky
</blockquote></details>

Fixed

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1)* status: 105 of 107 files reviewed, 3 unresolved discussions (waiting on @hettlage, @mofokeng-chaka, and @saltastroops)

___
*[src/imephu/finder_chart.py, line 62 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutmjWZCVHeGTW_bshM:-Muuwdrk9Q5GYXBHfkN4:bih716s) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/finder_chart.py#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No need. The joy of AstroPy quantities is that you specify them along with units.
</blockquote></details>

Yep, you're right.
___
*[src/imephu/annotation/general/arrow.py, line 26 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-MutrKdADdRkcbQCX3YF:-MuuvJUm3cSKM_x7eLTM:bvyqakm) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/annotation/general/arrow.py#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually I think my version is correct
</blockquote></details>

Alright, it just sounded weird at first but maybe you're probably right.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1)* status: all files reviewed, 3 unresolved discussions (waiting on @saltastroops)

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r6, 34 of 34 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1)* status: all files reviewed, 5 unresolved discussions (waiting on @saltastroops)

___
*[setup.cfg, line 141 at r7](https://reviewable.io/reviews/saltastroops/imephu/1#-MvHerKVE-2eze72gO_9:-MvHerKWEzDWy19WZeLi:bjk3obb) ([raw file](https://github.com/saltastroops/imephu/blob/418d21145a6ce325590ed8adc3a771f9a3948ffb/setup.cfg#L141)):*
> ```INI
>     defusedxml
>     matplotlib
>     pikepdf
> ```

Another problem I ran into is that when I ran the tests they were failing because `pikepdf` and `matplotlib` modules were missing. I had to first install them manually, so does them being listed in this here mean that they are expected to be installed on my laptop already? Should they be listed in `requirements-dev.txt` as well?
___
*[src/imephu/annotation/motion.py, line 125 at r7](https://reviewable.io/reviews/saltastroops/imephu/1#-MvHbK7kAIOqYlC7Yi6c:-MvHbK7lELxHlz_bFFep:b-5zwr2o) ([raw file](https://github.com/saltastroops/imephu/blob/418d21145a6ce325590ed8adc3a771f9a3948ffb/src/imephu/annotation/motion.py#L125)):*
> ```Python
> 
>     # calculate an arrow start and end so that the arrow head will be placed at the
>     # right direction abd will point in the right direction
> ```

# right direction and will ...
___
*[src/imephu/annotation/motion.py, line 239 at r7](https://reviewable.io/reviews/saltastroops/imephu/1#-MvHc2NI6Y02iGDF632x:-MvHc2NJ5rbJcGXcD-Se:bf5rjer) ([raw file](https://github.com/saltastroops/imephu/blob/418d21145a6ce325590ed8adc3a771f9a3948ffb/src/imephu/annotation/motion.py#L239)):*
> ```Python
>     """Return the angle per pixel for a WCS object.
> 
>     The angle per pixel is averaged over right ascension abd declination.
> ```

right ascension and declination

**Review by mofokeng-chaka — COMMENTED** [review]
Some modules are incorrectly imported in the `~/tests/conftest.py` file, and they are not being utilized anywhere in the script.

Also, I am not sure probably we discussed this previously but `mypy` seems to be complaining about the return type of the unit test functions and I realized that all of them have no return. Is this intended? and so we should ignore warnings from `mypy`?

> Reviewed 1 of 2 files at r8, 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1#-:-Mvb0G6q0hka6xld0QXY:b-qlf8hl)* status: all files reviewed, 5 unresolved discussions (waiting on @saltastroops)

**Review by hettlage — APPROVED** [review]
> Reviewed 16 of 104 files at r1, 5 of 11 files at r2, 4 of 15 files at r6, 5 of 34 files at r7, 1 of 2 files at r8, 4 of 7 files at r9, 104 of 104 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/1)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka and @saltastroops)

___
*[setup.cfg, line 141 at r7](https://reviewable.io/reviews/saltastroops/imephu/1#-MvHerKVE-2eze72gO_9:-MvKt8qq7l96a0MaZNCU:b-md1nvu) ([raw file](https://github.com/saltastroops/imephu/blob/418d21145a6ce325590ed8adc3a771f9a3948ffb/setup.cfg#L141)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Another problem I ran into is that when I ran the tests they were failing because `pikepdf` and `matplotlib` modules were missing. I had to first install them manually, so does them being listed in this here mean that they are expected to be installed on my laptop already? Should they be listed in `requirements-dev.txt` as well?
</blockquote></details>

It means that tests run with tox should run as expected, as tox will install all these requirements.
___
*[src/imephu/annotation/motion.py, line 125 at r7](https://reviewable.io/reviews/saltastroops/imephu/1#-MvHbK7kAIOqYlC7Yi6c:-MvKuLaGE9JmX2fSks_T:b-d5q2ho) ([raw file](https://github.com/saltastroops/imephu/blob/418d21145a6ce325590ed8adc3a771f9a3948ffb/src/imephu/annotation/motion.py#L125)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

# right direction and will ...
</blockquote></details>

Fixed. Thanks.
___
*[src/imephu/annotation/motion.py, line 239 at r7](https://reviewable.io/reviews/saltastroops/imephu/1#-MvHc2NI6Y02iGDF632x:-MvKuTtj48vJaObN8wWn:b-d5q2ho) ([raw file](https://github.com/saltastroops/imephu/blob/418d21145a6ce325590ed8adc3a771f9a3948ffb/src/imephu/annotation/motion.py#L239)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

right ascension and declination
</blockquote></details>

Fixed. Thanks.
___
*[src/imephu/service/survey.py, line 159 at r1](https://reviewable.io/reviews/saltastroops/imephu/1#-Mutw5CN3ZjK5guK9x5c:-MvKulYD9c4e3PsyKgXt:bt2vr1b) ([raw file](https://github.com/saltastroops/imephu/blob/9939b57455a5d64303bebe756991fce20ef4e631/src/imephu/service/survey.py#L159)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

"The" probably doesn't belong here or you forgot to finish up the sentence.
</blockquote></details>

Fixed.

**Pull request merged**
