### PR TITLE
Command line interface

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/imephu/7)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/7)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @hettlage and @mofokeng-chaka)

___
*[tests/conftest.py, line 84 at r1](https://reviewable.io/reviews/saltastroops/imephu/7#-Mw_zDQbEpKun1WPTkOm:-Mw_zDQoCONu2fT4c4WR:b-t23lpm) ([raw file](https://github.com/saltastroops/imephu/blob/bca272a4c38548190df01a9f5c1909eac3514a7a/tests/conftest.py#L84)):*
> ```Python
>     Parameters
>     ----------
>     tmp_path_factory: fixture for creating as temporary directory
> ```

as > a

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/7)* status: 11 of 33 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[tests/conftest.py, line 84 at r1](https://reviewable.io/reviews/saltastroops/imephu/7#-Mw_zDQbEpKun1WPTkOm:-Mwcs-V00D4DULeHoEmf:b-d5q2i1) ([raw file](https://github.com/saltastroops/imephu/blob/bca272a4c38548190df01a9f5c1909eac3514a7a/tests/conftest.py#L84)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

as > a
</blockquote></details>

Fixed. Thanks!

**Review by mofokeng-chaka — APPROVED** [review]
:lgtm:

> Reviewed 1 of 18 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/7#-:-Mwg3RYw-UVt17D2O4Qq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/imephu/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
